# Generated by Django 5.2 on 2025-04-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmmausFrontEnd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatheringInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("date", models.CharField(max_length=200)),
                ("cluster", models.CharField(max_length=200)),
            ],
        ),
    ]
