# Generated by Django 5.2 on 2025-04-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmmausFrontEnd", "0002_gatheringinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatheringinformation",
            name="time",
            field=models.CharField(default="6pm - 9pm", max_length=200),
            preserve_default=False,
        ),
    ]
