# Generated by Django 5.2 on 2025-04-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmmausFrontEnd", "0003_gatheringinformation_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_position", models.CharField(max_length=200)),
                ("member", models.CharField(max_length=200)),
                ("year", models.CharField(max_length=200)),
            ],
        ),
    ]
