# Generated by Django 5.2 on 2025-04-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmmausFrontEnd", "0004_boardmembers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pilgrim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pilgrim_name", models.CharField(max_length=200)),
                ("walk_number", models.CharField(max_length=200)),
                ("walk_group", models.CharField(max_length=200)),
            ],
        ),
    ]
