# Generated by Django 5.2 on 2025-04-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EmmausFrontEnd", "0005_pilgrim"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BoardMembers",
            new_name="BoardMember",
        ),
    ]
