# Generated by Django 5.2 on 2025-04-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmmausFrontEnd", "0006_rename_boardmembers_boardmember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("walk_number", models.CharField(max_length=200)),
                ("walk_group", models.CharField(max_length=200)),
                ("start_date", models.CharField(max_length=200)),
                ("end_date", models.CharField(max_length=200)),
            ],
        ),
    ]
